### ISSUE TITLE
最低支持的api？

### ISSUE THREAD

**Issue by xiang23** [LanSoSdk/LanSoEditor_common#10]
是sdk里面写的18吗？

**Comment by xiang23** [comment]
另外不支持x86?没有module里面没有so

**Comment by LanSoSdk** [comment]
感谢你的使用。

1， 是sdk里面写的18吗？  <------是的 ， 我们SDK 的最低版本是android4.3 ； 不支持4.3一下的版本；

2，不支持x86?没有module里面没有写x86的so<------------------我们没有做x86的so， 因为没有这样的手机， 如果你有特殊需求， 可以联系我们， 为您定制。谢谢。
