### ISSUE TITLE
MP3合成问题

### ISSUE THREAD

**Issue by CatyVon** [LanSoSdk/LanSoEditor_common#16]
您好  我这边有个功能需求  用户自行录制N段MP3  就是子MP3文件  然后将这些子文件合成到一个固定的背景MP3音轨中  因为后台有指定这些子文件的开始结束时间  所以不能一个挨着一个  需要在背景MP3上的指定位置插入合成这些子文件  这个该如何实现呢  麻烦了

**Comment by vigrep** [comment]
@CatyVon 你好，我也有类似的需求，你解决吗？

**Comment by LanSoSdk** [comment]
请用我们专业版里的音频容器，audiopadexecute，这是一个容器，你可以在任意时刻插入任意一段音频，并可以调节音量，变声等。

**Comment by LanSoSdk** [comment]
我们的专业版里的audiopadexecute在下周会整理到基本版本，敬请等待

**Comment by vigrep** [comment]
好的，谢谢。

**Comment by CatyVon** [comment]
最后项目放弃了这个功能  也是因为没有合适的解决方案

发送自 Windows 10 版邮件应用

发件人: vigrep
发送时间: 2019年2月13日 12:21
收件人: LanSoSdk/LanSoEditor_common
抄送: Monce; Mention
主题: Re: [LanSoSdk/LanSoEditor_common] MP3合成问题 (#16)

@CatyVon 你好，我也有类似的需求，你解决吗？

**Comment by LanSoSdk** [comment]
> 好的，谢谢。

SDK已经把音频容器类放到这个容器里了,请下载测试, 谢谢

**Comment by LanSoSdk** [comment]
@vigrep SDK已经把音频容器类放到这个容器里了,请下载测试, 谢谢
