### ISSUE TITLE
执行自定义的ffmpeg指令 native中的excute 返回  1

### ISSUE THREAD

**Issue by caizhixing** [LanSoSdk/LanSoEditor_common#96]
感谢你们的sdk。测试时发现有个小问题。直接进入初始化好lansongsdk的的app ，执行自定义指令（指令为获取音频的频谱）发现native方法一直返回 1。但是，如果执行了sdk中已存在的音频剪切方法后，再执行自定义指令，能够返回期待的结果。所以我想问一下，如果想执行自定义的指令，是需要手动初始化什么吗？谢谢

**Comment by LanSoSdk** [comment]
不需要,直接按照我们VideoEditor.java或AudioEditor.java中的形式做下去,就可以了
